spring.datasource.url=jdbc:mysql://YOUR_MYSQL_PUBLIC_URL?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=vZidDVghCRFMHCsQBibEBCfDoWeqRQTx

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}
