spring.datasource.url=jdbc:mysql://caboose.proxy.rlwy.net:53072/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=vZidDvghCRFMHCsQBibEBCfDoWeqRQTx

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=${PORT:8080}
